apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
springData:
{{- range $key, $value := .Values.secrets }}
  {{ $key | upper }}: {{ $value | quote }}
{{- end }}