apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
springData:
  POSTGRES_USERNAME: {{ .Values.secrets.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.password | quote }}