apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-infra-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-infra-user
      tier: backend
  template:
    metadata:
      labels:
        app: demo-infra-user
        tier: backend  
    spec:
      containers:
        - name: demo-infra-user
          image: demo-infra-user
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"