replicaCount: 2

image: 
  repository: issakhrorov/demo-infra
  tag: "user-service-41577f6"
  pullPolicy: IfNotPresent
service:
  type: ClusterIp
  port: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
env:
  SPRING_PROFILES_ACTIVE: "docker"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  DB_NAME: demo_infra_user
  KAFKA_BOOTSTRAP_SERVERS: "192.168.0.149:29091,192.168.0.149:29092,192.168.0.149:29093"
  PRODUCER_SCHEMA_REGISTRY_HOST: "http://192.168.0.149:9011"
  CONSUMER_SCHEMA_REGISTRY_HOST: "http://192.168.0.149:9011"

secrets:
  pg_username: "issakhrorov"
  pg_password: "1111"

livenessProbe:
  path: /actuator/health/liveness
  port: 8080
readinessProbe:
  path: /actuator/health/readiness
  port: 8080
