replicaCount: 1
image:
  repository: issakhrorov/demo-infra
  tag: "user-service-41577f6"
  pullPolicy: IfNotPresent
service:
  type: ClusterIp
  port: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
env:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/demo-infra-user"
  SPRING_DATASOURCE_USERNAME: "issakhrorov"
  SPRING_DATASOURCE_PASSWORD: "1111"
livenessProbe:
  path: /actuator/health/liveness
  port: 8080
readinessProbe:
  path: /actuator/health/readiness
  port: 8080
